import 'package:pavilion_rewards_ui/exports/file_exports.dart';

final List<TransactionCard> transHistory = [
  TransactionCard(
    url: 'assets/icons/success_gift.svg',
    points: '+50points',
    title: 'SuperMart',
    date: '12/06/2022',
    time: '12:34',
    isSuccess: true,
  ),
  TransactionCard(
    url: 'assets/icons/failure_gift.svg',
    points: '+50points',
    title: 'SuperMart',
    date: '12/06/2022',
    time: '12:34',
    isSuccess: false,
  ),
  TransactionCard(
    url: 'assets/icons/failure_gift.svg',
    points: '+50points',
    title: 'SuperMart',
    date: '12/06/2022',
    time: '12:34',
    isSuccess: false,
  ),
  TransactionCard(
    url: 'assets/icons/success_gift.svg',
    points: '+50points',
    title: 'SuperMart',
    date: '12/06/2022',
    time: '12:34',
    isSuccess: true,
  ),
  TransactionCard(
    url: 'assets/icons/failure_gift.svg',
    points: '+50points',
    title: 'SuperMart',
    date: '12/06/2022',
    time: '12:34',
    isSuccess: false,
  ),
  TransactionCard(
    url: 'assets/icons/failure_gift.svg',
    points: '+50points',
    title: 'SuperMart',
    date: '12/06/2022',
    time: '12:34',
    isSuccess: false,
  ),
  TransactionCard(
    url: 'assets/icons/failure_gift.svg',
    points: '+50points',
    title: 'SuperMart',
    date: '12/06/2022',
    time: '12:34',
    isSuccess: false,
  ),
  TransactionCard(
    url: 'assets/icons/failure_gift.svg',
    points: '+50points',
    title: 'SuperMart',
    date: '12/06/2022',
    time: '12:34',
    isSuccess: true,
  ),
  TransactionCard(
    url: 'assets/icons/failure_gift.svg',
    points: '+50points',
    title: 'SuperMart',
    date: '12/06/2022',
    time: '12:34',
    isSuccess: false,
  ),
  TransactionCard(
    url: 'assets/icons/failure_gift.svg',
    points: '+50points',
    title: 'SuperMart',
    date: '12/06/2022',
    time: '12:34',
    isSuccess: true,
  ),
  TransactionCard(
    url: 'assets/icons/failure_gift.svg',
    points: '+50points',
    title: 'SuperMart',
    date: '12/06/2022',
    time: '12:34',
    isSuccess: false,
  ),
  TransactionCard(
    url: 'assets/icons/failure_gift.svg',
    points: '+50points',
    title: 'SuperMart',
    date: '12/06/2022',
    time: '12:34',
    isSuccess: true,
  ),
  TransactionCard(
    url: 'assets/icons/failure_gift.svg',
    points: '+50points',
    title: 'SuperMart',
    date: '12/06/2022',
    time: '12:34',
    isSuccess: false,
  ),
];
